// AUTO-GENERATED by scripts/pre-build-data.js — DO NOT EDIT MANUALLY
// This file contains ONLY structure data. Content is loaded lazily from JSON files.

export interface GeneratedFormation {
  id: string
  name: string
  niveaux: {
    id: string
    name: string
    episodes: { slug: string; title: string }[]
  }[]
}

export const formations: GeneratedFormation[] = [
  {
    "id": "formation-1-musulman",
    "name": "musulman",
    "niveaux": [
      {
        "id": "niveau-1",
        "name": "niveau 1",
        "episodes": [
          {
            "slug": "formation-1-musulman/niveau-1/episode-01-pourquoi-votre-lecture-du-coran-vous-laisse-insatisfait.md",
            "title": "01. Pourquoi votre lecture du coran vous laisse insatisfait"
          },
          {
            "slug": "formation-1-musulman/niveau-1/episode-02-les-fondations-5-regles-d-or.md",
            "title": "02. Les fondations 5 regles d or"
          },
          {
            "slug": "formation-1-musulman/niveau-1/episode-03-fana-faire-taire-le-bruit-de-legalo.md",
            "title": "03. Fana faire taire le bruit de legalo"
          },
          {
            "slug": "formation-1-musulman/niveau-1/episode-04-tajalli-quand-le-verset-vous-lit.md",
            "title": "04. Tajalli quand le verset vous lit"
          },
          {
            "slug": "formation-1-musulman/niveau-1/episode-05-munajat-le-dialogue-intime-avec-allah.md",
            "title": "05. Munajat le dialogue intime avec allah"
          },
          {
            "slug": "formation-1-musulman/niveau-1/episode-06-la-beance-le-silence-ou-dieu-se-trouve.md",
            "title": "06. La beance le silence ou dieu se trouve"
          },
          {
            "slug": "formation-1-musulman/niveau-1/episode-07-programme-21-jours-immersion-guidee.md",
            "title": "07. Programme 21 jours immersion guidee"
          },
          {
            "slug": "formation-1-musulman/niveau-1/episode-08-pieges-blocages-et-comment-les-depasser.md",
            "title": "08. Pieges blocages et comment les depasser"
          }
        ]
      },
      {
        "id": "niveau-2",
        "name": "niveau 2",
        "episodes": [
          {
            "slug": "formation-1-musulman/niveau-2/episode-01-al-fatiha-versets-1-3.md",
            "title": "01. Al fatiha versets 1 3"
          },
          {
            "slug": "formation-1-musulman/niveau-2/episode-02-al-fatiha-versets-4-5.md",
            "title": "02. Al fatiha versets 4 5"
          },
          {
            "slug": "formation-1-musulman/niveau-2/episode-03-al-fatiha-versets-6-7.md",
            "title": "03. Al fatiha versets 6 7"
          },
          {
            "slug": "formation-1-musulman/niveau-2/episode-04-tresors-versets-peur-et-anxiete.md",
            "title": "04. Tresors versets peur et anxiete"
          },
          {
            "slug": "formation-1-musulman/niveau-2/episode-05-tresors-versets-tristesse-et-deuil.md",
            "title": "05. Tresors versets tristesse et deuil"
          },
          {
            "slug": "formation-1-musulman/niveau-2/episode-06-tresors-versets-colere-et-culpabilite.md",
            "title": "06. Tresors versets colere et culpabilite"
          },
          {
            "slug": "formation-1-musulman/niveau-2/episode-07-noms-divins-outils-de-transformation.md",
            "title": "07. Noms divins outils de transformation"
          },
          {
            "slug": "formation-1-musulman/niveau-2/episode-08-pratique-quotidienne-avancee.md",
            "title": "08. Pratique quotidienne avancee"
          }
        ]
      },
      {
        "id": "niveau-3",
        "name": "niveau 3",
        "episodes": [
          {
            "slug": "formation-1-musulman/niveau-3/episode-01-le-point-noir-fana-intensif.md",
            "title": "01. Le point noir fana intensif"
          },
          {
            "slug": "formation-1-musulman/niveau-3/episode-02-le-dhikr-du-coeur.md",
            "title": "02. Le dhikr du coeur"
          },
          {
            "slug": "formation-1-musulman/niveau-3/episode-03-noms-divins-inversion-avancee.md",
            "title": "03. Noms divins inversion avancee"
          },
          {
            "slug": "formation-1-musulman/niveau-3/episode-04-les-etats-spirituels.md",
            "title": "04. Les etats spirituels"
          },
          {
            "slug": "formation-1-musulman/niveau-3/episode-05-qiyam-al-layl.md",
            "title": "05. Qiyam al layl"
          },
          {
            "slug": "formation-1-musulman/niveau-3/episode-06-muraqaba-la-veille-du-coeur.md",
            "title": "06. Muraqaba la veille du coeur"
          },
          {
            "slug": "formation-1-musulman/niveau-3/episode-07-les-4-phases-integrees.md",
            "title": "07. Les 4 phases integrees"
          },
          {
            "slug": "formation-1-musulman/niveau-3/episode-08-programme-40-jours.md",
            "title": "08. Programme 40 jours"
          }
        ]
      }
    ]
  },
  {
    "id": "formation-2-musulman-professionnel",
    "name": "musulman professionnel",
    "niveaux": [
      {
        "id": "niveau-1",
        "name": "niveau 1",
        "episodes": [
          {
            "slug": "formation-2-musulman-professionnel/niveau-1/episode-01-pourquoi-votre-spiritualite-ne-survit-pas-au-travail.md",
            "title": "01. Pourquoi votre spiritualite ne survit pas au travail"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-1/episode-02-les-fondations-5-regles-pour-le-pro.md",
            "title": "02. Les fondations 5 regles pour le pro"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-1/episode-03-fana-leffacement-entre-deux-reunions.md",
            "title": "03. Fana leffacement entre deux reunions"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-1/episode-04-tajalli-le-coran-au-bureau.md",
            "title": "04. Tajalli le coran au bureau"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-1/episode-05-munajat-decisions-difficiles.md",
            "title": "05. Munajat decisions difficiles"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-1/episode-06-la-beance-le-silence-au-travail.md",
            "title": "06. La beance le silence au travail"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-1/episode-07-programme-14-jours-integration-pro.md",
            "title": "07. Programme 14 jours integration pro"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-1/episode-08-pieges-du-professionnel.md",
            "title": "08. Pieges du professionnel"
          }
        ]
      },
      {
        "id": "niveau-2",
        "name": "niveau 2",
        "episodes": [
          {
            "slug": "formation-2-musulman-professionnel/niveau-2/episode-01-al-fatiha-versets-1-3-sens-au-travail.md",
            "title": "01. Al fatiha versets 1 3 sens au travail"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-2/episode-02-al-fatiha-versets-4-5-servitude-et-guidance.md",
            "title": "02. Al fatiha versets 4 5 servitude et guidance"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-2/episode-03-al-fatiha-versets-6-7-deux-extremes.md",
            "title": "03. Al fatiha versets 6 7 deux extremes"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-2/episode-04-tresors-burnout-et-epuisement.md",
            "title": "04. Tresors burnout et epuisement"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-2/episode-05-tresors-syndrome-imposteur.md",
            "title": "05. Tresors syndrome imposteur"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-2/episode-06-tresors-conflits-et-autorite.md",
            "title": "06. Tresors conflits et autorite"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-2/episode-07-noms-divins-outils-de-leadership.md",
            "title": "07. Noms divins outils de leadership"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-2/episode-08-pratique-integree-avancee.md",
            "title": "08. Pratique integree avancee"
          }
        ]
      },
      {
        "id": "niveau-3",
        "name": "niveau 3",
        "episodes": [
          {
            "slug": "formation-2-musulman-professionnel/niveau-3/episode-01-point-noir-pro.md",
            "title": "01. Point noir pro"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-3/episode-02-dhikr-du-coeur-au-bureau.md",
            "title": "02. Dhikr du coeur au bureau"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-3/episode-02-dhikrru-coeur-au-bureau.md",
            "title": "02. Dhikrru coeur au bureau"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-3/episode-03-inversion-avancee.md",
            "title": "03. Inversion avancee"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-3/episode-04-etats-spirituels-au-travail.md",
            "title": "04. Etats spirituels au travail"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-3/episode-05-qiyam-adapte-pour-les-pros.md",
            "title": "05. Qiyam adapte pour les pros"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-3/episode-06-muraqaba-pro.md",
            "title": "06. Muraqaba pro"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-3/episode-07-seance-integree.md",
            "title": "07. Seance integree"
          },
          {
            "slug": "formation-2-musulman-professionnel/niveau-3/episode-08-programme-40-jours-pro.md",
            "title": "08. Programme 40 jours pro"
          }
        ]
      }
    ]
  },
  {
    "id": "formation-3-tout-public",
    "name": "tout public",
    "niveaux": [
      {
        "id": "nuveau-3",
        "name": "nuveau 3",
        "episodes": [
          {
            "slug": "formation-3-tout-public/nuveau-3/episode-05-meditation-avancee.md",
            "title": "05. Meditation avancee"
          }
        ]
      },
      {
        "id": "niveau-1",
        "name": "niveau 1",
        "episodes": [
          {
            "slug": "formation-3-tout-public/niveau-1/episode-01-pourquoi-la-spiritualite-est-elle-importante.md",
            "title": "01. Pourquoi la spiritualite est elle importante"
          },
          {
            "slug": "formation-3-tout-public/niveau-1/episode-02-les-fondations-cinq-pratiques.md",
            "title": "02. Les fondations cinq pratiques"
          },
          {
            "slug": "formation-3-tout-public/niveau-1/episode-03-le-silence-interieur.md",
            "title": "03. Le silence interieur"
          },
          {
            "slug": "formation-3-tout-public/niveau-1/episode-04-tajalli-les-moments-de-clarte.md",
            "title": "04. Tajalli les moments de clarte"
          },
          {
            "slug": "formation-3-tout-public/niveau-1/episode-05-munajat-le-dialogue-avec-votre-sagesse.md",
            "title": "05. Munajat le dialogue avec votre sagesse"
          },
          {
            "slug": "formation-3-tout-public/niveau-1/episode-06-la-beance-lespace-de-transformation.md",
            "title": "06. La beance lespace de transformation"
          },
          {
            "slug": "formation-3-tout-public/niveau-1/episode-07-programme-14-jours.md",
            "title": "07. Programme 14 jours"
          },
          {
            "slug": "formation-3-tout-public/niveau-1/episode-08-pieges-et-blocages.md",
            "title": "08. Pieges et blocages"
          }
        ]
      },
      {
        "id": "niveau-2",
        "name": "niveau 2",
        "episodes": [
          {
            "slug": "formation-3-tout-public/niveau-2/episode-01-accueillir-les-emotions-sans-se-laisser-submerger.md",
            "title": "01. Accueillir les emotions sans se laisser submerger"
          },
          {
            "slug": "formation-3-tout-public/niveau-2/episode-01-accueillir-les-emotions.md",
            "title": "01. Accueillir les emotions"
          },
          {
            "slug": "formation-3-tout-public/niveau-2/episode-02-transformer-la-peur-en-force-science-du-courage.md",
            "title": "02. Transformer la peur en force science du courage"
          },
          {
            "slug": "formation-3-tout-public/niveau-2/episode-02-transformer-la-peur.md",
            "title": "02. Transformer la peur"
          },
          {
            "slug": "formation-3-tout-public/niveau-2/episode-03-les-relations-difficiles-communication-et-compassion.md",
            "title": "03. Les relations difficiles communication et compassion"
          },
          {
            "slug": "formation-3-tout-public/niveau-2/episode-03-relations-difficiles.md",
            "title": "03. Relations difficiles"
          },
          {
            "slug": "formation-3-tout-public/niveau-2/episode-04-le-sens-de-la-vie-construire-un-pourquoi.md",
            "title": "04. Le sens de la vie construire un pourquoi"
          },
          {
            "slug": "formation-3-tout-public/niveau-2/episode-04-le-sens-de-la-vie.md",
            "title": "04. Le sens de la vie"
          },
          {
            "slug": "formation-3-tout-public/niveau-2/episode-05-la-resilience-rebondir-apres-epreuve.md",
            "title": "05. La resilience rebondir apres epreuve"
          },
          {
            "slug": "formation-3-tout-public/niveau-2/episode-05-la-resilience.md",
            "title": "05. La resilience"
          },
          {
            "slug": "formation-3-tout-public/niveau-2/episode-06-le-lacher-prise-detachement-et-confiance.md",
            "title": "06. Le lacher prise detachement et confiance"
          },
          {
            "slug": "formation-3-tout-public/niveau-2/episode-06-le-lacher-prise.md",
            "title": "06. Le lacher prise"
          },
          {
            "slug": "formation-3-tout-public/niveau-2/episode-07-pratiques-avancees-micro-retraite-et-techniques.md",
            "title": "07. Pratiques avancees micro retraite et techniques"
          },
          {
            "slug": "formation-3-tout-public/niveau-2/episode-07-pratiques-avancees.md",
            "title": "07. Pratiques avancees"
          },
          {
            "slug": "formation-3-tout-public/niveau-2/episode-08-seance-integree-n2.md",
            "title": "08. Seance integree n2"
          },
          {
            "slug": "formation-3-tout-public/niveau-2/episode-08-seance-integree-routine-complete-de-la-journee.md",
            "title": "08. Seance integree routine complete de la journee"
          }
        ]
      },
      {
        "id": "niveau-3",
        "name": "niveau 3",
        "episodes": [
          {
            "slug": "formation-3-tout-public/niveau-3/episode-01-votre-point-faible.md",
            "title": "01. Votre point faible"
          },
          {
            "slug": "formation-3-tout-public/niveau-3/episode-02-presence-au-quotidien.md",
            "title": "02. Presence au quotidien"
          },
          {
            "slug": "formation-3-tout-public/niveau-3/episode-03-pensees-negatives-inversion.md",
            "title": "03. Pensees negatives inversion"
          },
          {
            "slug": "formation-3-tout-public/niveau-3/episode-04-les-etats-de-conscience-flow.md",
            "title": "04. Les etats de conscience flow"
          },
          {
            "slug": "formation-3-tout-public/niveau-3/episode-05-meditation-avancee.md",
            "title": "05. Meditation avancee"
          },
          {
            "slug": "formation-3-tout-public/niveau-3/episode-06-la-pratique-du-matin-integrale-routine-complete.md",
            "title": "06. La pratique du matin integrale routine complete"
          },
          {
            "slug": "formation-3-tout-public/niveau-3/episode-07-seance-integree.md",
            "title": "07. Seance integree"
          },
          {
            "slug": "formation-3-tout-public/niveau-3/episode-08-programme-40-jours.md",
            "title": "08. Programme 40 jours"
          }
        ]
      }
    ]
  },
  {
    "id": "formation-4-pro-tout-public",
    "name": "pro tout public",
    "niveaux": [
      {
        "id": "niveau-1",
        "name": "niveau 1",
        "episodes": [
          {
            "slug": "formation-4-pro-tout-public/niveau-1/episode-01-pourquoi-spiritualite-pro.md",
            "title": "01. Pourquoi spiritualite pro"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-1/episode-02-fondations-pro.md",
            "title": "02. Fondations pro"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-1/episode-03-le-silence-interieur-pro.md",
            "title": "03. Le silence interieur pro"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-1/episode-04-tajalli-bureau.md",
            "title": "04. Tajalli bureau"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-1/episode-05-munajat-decisions.md",
            "title": "05. Munajat decisions"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-1/episode-06-lespace-de-transformation-pro.md",
            "title": "06. Lespace de transformation pro"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-1/episode-07-programme-14-jours-pro.md",
            "title": "07. Programme 14 jours pro"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-1/episode-08-seance-integree-initiation-pro.md",
            "title": "08. Seance integree initiation pro"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-1/episode-08-seance-n2-pro.md",
            "title": "08. Seance n2 pro"
          }
        ]
      },
      {
        "id": "niveau-2",
        "name": "niveau 2",
        "episodes": [
          {
            "slug": "formation-4-pro-tout-public/niveau-2/episode-01-burnout-pro.md",
            "title": "01. Burnout pro"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-2/episode-02-imposteur-pro.md",
            "title": "02. Imposteur pro"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-2/episode-03-leadership-empathie.md",
            "title": "03. Leadership empathie"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-2/episode-04-conflits-pro.md",
            "title": "04. Conflits pro"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-2/episode-05-sens-travail.md",
            "title": "05. Sens travail"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-2/episode-06-resilience-pro.md",
            "title": "06. Resilience pro"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-2/episode-07-pratiques-avancees-pro.md",
            "title": "07. Pratiques avancees pro"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-2/episode-08-seance-n2-pro.md",
            "title": "08. Seance n2 pro"
          }
        ]
      },
      {
        "id": "niveau-3",
        "name": "niveau 3",
        "episodes": [
          {
            "slug": "formation-4-pro-tout-public/niveau-3/episode-01-point-faible-pro.md",
            "title": "01. Point faible pro"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-3/episode-02-presence-pro.md",
            "title": "02. Presence pro"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-3/episode-03-pensees-negatives-pro.md",
            "title": "03. Pensees negatives pro"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-3/episode-04-etats-flow-pro.md",
            "title": "04. Etats flow pro"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-3/episode-05-meditation-avancee-pro.md",
            "title": "05. Meditation avancee pro"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-3/episode-06-routine-matinale-pro.md",
            "title": "06. Routine matinale pro"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-3/episode-07-seance-integree-pro.md",
            "title": "07. Seance integree pro"
          },
          {
            "slug": "formation-4-pro-tout-public/niveau-3/episode-08-programme-40-jours-pro.md",
            "title": "08. Programme 40 jours pro"
          }
        ]
      }
    ]
  },
  {
    "id": "formation-5-parents-musulmans",
    "name": "parents musulmans",
    "niveaux": [
      {
        "id": "niveau-1-compagnonnage-spirituel",
        "name": "compagnonnage spirituel",
        "episodes": [
          {
            "slug": "formation-5-parents-musulmans/niveau-1-compagnonnage-spirituel/episode-01-ce-que-votre-ado-musulman-vit.md",
            "title": "01. Ce que votre ado musulman vit"
          },
          {
            "slug": "formation-5-parents-musulmans/niveau-1-compagnonnage-spirituel/episode-02-votre-ado-vous-lit-avant-de-lire-le-coran.md",
            "title": "02. Votre ado vous lit avant de lire le coran"
          },
          {
            "slug": "formation-5-parents-musulmans/niveau-1-compagnonnage-spirituel/episode-03-votre-ado-est-en-guerre-avec-deux-mondes.md",
            "title": "03. Votre ado est en guerre avec deux mondes"
          },
          {
            "slug": "formation-5-parents-musulmans/niveau-1-compagnonnage-spirituel/episode-04-quil-prie-5-fois-ou-0-fois.md",
            "title": "04. Quil prie 5 fois ou 0 fois"
          },
          {
            "slug": "formation-5-parents-musulmans/niveau-1-compagnonnage-spirituel/episode-05-quand-la-porte-claque.md",
            "title": "05. Quand la porte claque"
          },
          {
            "slug": "formation-5-parents-musulmans/niveau-1-compagnonnage-spirituel/episode-06-langoisse-nest-pas-un-manque-de-foi.md",
            "title": "06. Langoisse nest pas un manque de foi"
          },
          {
            "slug": "formation-5-parents-musulmans/niveau-1-compagnonnage-spirituel/episode-07-ce-que-votre-ado-cherche-sur-son-telephone.md",
            "title": "07. Ce que votre ado cherche sur son telephone"
          },
          {
            "slug": "formation-5-parents-musulmans/niveau-1-compagnonnage-spirituel/episode-08-devenir-le-parent-qui-accompagne.md",
            "title": "08. Devenir le parent qui accompagne"
          }
        ]
      }
    ]
  },
  {
    "id": "formation-6-parents-tout-public",
    "name": "parents tout public",
    "niveaux": [
      {
        "id": "niveau-1-presence-parentale",
        "name": "presence parentale",
        "episodes": [
          {
            "slug": "formation-6-parents-tout-public/niveau-1-presence-parentale/episode-01-derriere-le-masque-de-votre-ado.md",
            "title": "01. Derriere le masque de votre ado"
          },
          {
            "slug": "formation-6-parents-tout-public/niveau-1-presence-parentale/episode-02-votre-ado-repete-ce-que-vous-navez-pas-regle.md",
            "title": "02. Votre ado repete ce que vous navez pas regle"
          },
          {
            "slug": "formation-6-parents-tout-public/niveau-1-presence-parentale/episode-03-limposteur-commence-a-14-ans.md",
            "title": "03. Limposteur commence a 14 ans"
          },
          {
            "slug": "formation-6-parents-tout-public/niveau-1-presence-parentale/episode-04-le-corps-de-votre-ado-parle.md",
            "title": "04. Le corps de votre ado parle"
          },
          {
            "slug": "formation-6-parents-tout-public/niveau-1-presence-parentale/episode-05-quand-votre-ado-vous-rejette.md",
            "title": "05. Quand votre ado vous rejette"
          },
          {
            "slug": "formation-6-parents-tout-public/niveau-1-presence-parentale/episode-06-lanxiete-a-quelque-chose-a-vous-dire.md",
            "title": "06. Lanxiete a quelque chose a vous dire"
          },
          {
            "slug": "formation-6-parents-tout-public/niveau-1-presence-parentale/episode-07-lennui-est-mort.md",
            "title": "07. Lennui est mort"
          },
          {
            "slug": "formation-6-parents-tout-public/niveau-1-presence-parentale/episode-08-vous-ne-pouvez-offrir-que-ce-que-vous-avez-cultive.md",
            "title": "08. Vous ne pouvez offrir que ce que vous avez cultive"
          }
        ]
      }
    ]
  },
  {
    "id": "formation-7-parents-musulmans-7-11",
    "name": "parents musulmans 7 11",
    "niveaux": [
      {
        "id": "niveau-1-la-preservation",
        "name": "la preservation",
        "episodes": [
          {
            "slug": "formation-7-parents-musulmans-7-11/niveau-1-la-preservation/episode-01-le-miroir-liquide-pourquoi-7-11-ans-est-la-periode-la-plus-dangereuse.md",
            "title": "01. Le miroir liquide pourquoi 7 11 ans est la periode la plus dangereuse"
          },
          {
            "slug": "formation-7-parents-musulmans-7-11/niveau-1-la-preservation/episode-02-la-premiere-chose-que-votre-enfant-perd.md",
            "title": "02. La premiere chose que votre enfant perd"
          },
          {
            "slug": "formation-7-parents-musulmans-7-11/niveau-1-la-preservation/episode-03-quand-vous-criez-le-cerveau-de-votre-enfant-se-recable.md",
            "title": "03. Quand vous criez le cerveau de votre enfant se recable"
          },
          {
            "slug": "formation-7-parents-musulmans-7-11/niveau-1-la-preservation/episode-04-lecran-ne-vole-pas-le-temps-mais-la-capacite-a-ressentir.md",
            "title": "04. Lecran ne vole pas le temps mais la capacite a ressentir"
          },
          {
            "slug": "formation-7-parents-musulmans-7-11/niveau-1-la-preservation/episode-05-le-dua-de-votre-enfant-ne-devrait-jamais-etre-une-performance.md",
            "title": "05. Le dua de votre enfant ne devrait jamais etre une performance"
          },
          {
            "slug": "formation-7-parents-musulmans-7-11/niveau-1-la-preservation/episode-06-la-fratrie-nest-pas-un-probleme-cest-le-laboratoire-ou-la-fitra-se-teste.md",
            "title": "06. La fratrie nest pas un probleme cest le laboratoire ou la fitra se teste"
          },
          {
            "slug": "formation-7-parents-musulmans-7-11/niveau-1-la-preservation/episode-07-votre-enfant-vit-dans-deux-mondes-et-la-porte-entre-les-deux-est-en-train-de-se-fermer.md",
            "title": "07. Votre enfant vit dans deux mondes et la porte entre les deux est en train de se fermer"
          },
          {
            "slug": "formation-7-parents-musulmans-7-11/niveau-1-la-preservation/episode-08-les-5-piliers-de-la-preservation-votre-checklist-avant-12-ans.md",
            "title": "08. Les 5 piliers de la preservation votre checklist avant 12 ans"
          }
        ]
      }
    ]
  },
  {
    "id": "formation-8-parents-tout-public-7-11",
    "name": "parents tout public 7 11",
    "niveaux": [
      {
        "id": "niveau-1-la-preservation",
        "name": "la preservation",
        "episodes": [
          {
            "slug": "formation-8-parents-tout-public-7-11/niveau-1-la-preservation/episode-01-la-fenetre-qui-ne-souvrira-quune-fois.md",
            "title": "01. La fenetre qui ne souvrira quune fois"
          },
          {
            "slug": "formation-8-parents-tout-public-7-11/niveau-1-la-preservation/episode-02-ca-va-les-12-emotions-desapprises.md",
            "title": "02. Ca va les 12 emotions desapprises"
          },
          {
            "slug": "formation-8-parents-tout-public-7-11/niveau-1-la-preservation/episode-03-votre-cerveau-sous-stress.md",
            "title": "03. Votre cerveau sous stress"
          },
          {
            "slug": "formation-8-parents-tout-public-7-11/niveau-1-la-preservation/episode-04-le-cerveau-face-aux-ecrans.md",
            "title": "04. Le cerveau face aux ecrans"
          },
          {
            "slug": "formation-8-parents-tout-public-7-11/niveau-1-la-preservation/episode-05-le-jeu-libre-est-un-acte-neurologique.md",
            "title": "05. Le jeu libre est un acte neurologique"
          },
          {
            "slug": "formation-8-parents-tout-public-7-11/niveau-1-la-preservation/episode-06-le-conflit-est-la-meilleure-ecole.md",
            "title": "06. Le conflit est la meilleure ecole"
          },
          {
            "slug": "formation-8-parents-tout-public-7-11/niveau-1-la-preservation/episode-07-lanxiete-de-performance-commence-a-8-ans.md",
            "title": "07. Lanxiete de performance commence a 8 ans"
          },
          {
            "slug": "formation-8-parents-tout-public-7-11/niveau-1-la-preservation/episode-08-les-5-competences-avant-12-ans.md",
            "title": "08. Les 5 competences avant 12 ans"
          }
        ]
      }
    ]
  },
  {
    "id": "formation-9-enfants-musulmans-9-12",
    "name": "enfants musulmans 9 12",
    "niveaux": [
      {
        "id": "niveau-1-le-voyage-du-miroir",
        "name": "le voyage du miroir",
        "episodes": [
          {
            "slug": "formation-9-enfants-musulmans-9-12/niveau-1-le-voyage-du-miroir/episode-01-ton-jardin-secret-territoire-1-l-appel.md",
            "title": "01. Ton jardin secret territoire 1 l appel"
          },
          {
            "slug": "formation-9-enfants-musulmans-9-12/niveau-1-le-voyage-du-miroir/episode-02-les-visiteurs-de-ton-jardin-territoire-2-la-carte.md",
            "title": "02. Les visiteurs de ton jardin territoire 2 la carte"
          },
          {
            "slug": "formation-9-enfants-musulmans-9-12/niveau-1-le-voyage-du-miroir/episode-03-quand-le-feu-monte-territoire-3-le-dragon.md",
            "title": "03. Quand le feu monte territoire 3 le dragon"
          },
          {
            "slug": "formation-9-enfants-musulmans-9-12/niveau-1-le-voyage-du-miroir/episode-04-la-salle-des-miroirs-territoire-4-les-amis.md",
            "title": "04. La salle des miroirs territoire 4 les amis"
          },
          {
            "slug": "formation-9-enfants-musulmans-9-12/niveau-1-le-voyage-du-miroir/episode-05-le-tresor-cache-territoire-5-la-gratitude.md",
            "title": "05. Le tresor cache territoire 5 la gratitude"
          },
          {
            "slug": "formation-9-enfants-musulmans-9-12/niveau-1-le-voyage-du-miroir/episode-06-la-nuit-etoilee-territoire-6-la-solitude.md",
            "title": "06. La nuit etoilee territoire 6 la solitude"
          },
          {
            "slug": "formation-9-enfants-musulmans-9-12/niveau-1-le-voyage-du-miroir/episode-07-le-labyrinthe-territoire-7-les-ecrans.md",
            "title": "07. Le labyrinthe territoire 7 les ecrans"
          },
          {
            "slug": "formation-9-enfants-musulmans-9-12/niveau-1-le-voyage-du-miroir/episode-08-la-cle-territoire-8-la-cloture.md",
            "title": "08. La cle territoire 8 la cloture"
          }
        ]
      }
    ]
  },
  {
    "id": "formation-10-enfants-tout-public-9-12",
    "name": "enfants tout public 9 12",
    "niveaux": [
      {
        "id": "niveau-1-le-voyage-du-miroir",
        "name": "le voyage du miroir",
        "episodes": [
          {
            "slug": "formation-10-enfants-tout-public-9-12/niveau-1-le-voyage-du-miroir/episode-01-ton-chateau-interieur.md",
            "title": "01. Ton chateau interieur"
          },
          {
            "slug": "formation-10-enfants-tout-public-9-12/niveau-1-le-voyage-du-miroir/episode-02-les-messagers-de-ton-corps.md",
            "title": "02. Les messagers de ton corps"
          },
          {
            "slug": "formation-10-enfants-tout-public-9-12/niveau-1-le-voyage-du-miroir/episode-03-quand-le-volcan-éclate.md",
            "title": "03. Quand le volcan éclate"
          },
          {
            "slug": "formation-10-enfants-tout-public-9-12/niveau-1-le-voyage-du-miroir/episode-04-les-amis-miroirs.md",
            "title": "04. Les amis miroirs"
          },
          {
            "slug": "formation-10-enfants-tout-public-9-12/niveau-1-le-voyage-du-miroir/episode-05-le-muscle-de-la-gratitude.md",
            "title": "05. Le muscle de la gratitude"
          },
          {
            "slug": "formation-10-enfants-tout-public-9-12/niveau-1-le-voyage-du-miroir/episode-06-quand-tu-te-sens-seul-e.md",
            "title": "06. Quand tu te sens seul e"
          },
          {
            "slug": "formation-10-enfants-tout-public-9-12/niveau-1-le-voyage-du-miroir/episode-07-le-labyrinthe-decran.md",
            "title": "07. Le labyrinthe decran"
          },
          {
            "slug": "formation-10-enfants-tout-public-9-12/niveau-1-le-voyage-du-miroir/episode-08-la-cle.md",
            "title": "08. La cle"
          }
        ]
      }
    ]
  }
] as GeneratedFormation[]

export const episodesIndex: Record<string, { title: string; meta: Record<string, string> }> = {
  "formation-1-musulman/niveau-1/episode-01-pourquoi-votre-lecture-du-coran-vous-laisse-insatisfait.md": {
    "title": "01. Pourquoi votre lecture du coran vous laisse insatisfait",
    "meta": {}
  },
  "formation-1-musulman/niveau-1/episode-02-les-fondations-5-regles-d-or.md": {
    "title": "02. Les fondations 5 regles d or",
    "meta": {}
  },
  "formation-1-musulman/niveau-1/episode-03-fana-faire-taire-le-bruit-de-legalo.md": {
    "title": "03. Fana faire taire le bruit de legalo",
    "meta": {}
  },
  "formation-1-musulman/niveau-1/episode-04-tajalli-quand-le-verset-vous-lit.md": {
    "title": "04. Tajalli quand le verset vous lit",
    "meta": {}
  },
  "formation-1-musulman/niveau-1/episode-05-munajat-le-dialogue-intime-avec-allah.md": {
    "title": "05. Munajat le dialogue intime avec allah",
    "meta": {}
  },
  "formation-1-musulman/niveau-1/episode-06-la-beance-le-silence-ou-dieu-se-trouve.md": {
    "title": "06. La beance le silence ou dieu se trouve",
    "meta": {}
  },
  "formation-1-musulman/niveau-1/episode-07-programme-21-jours-immersion-guidee.md": {
    "title": "07. Programme 21 jours immersion guidee",
    "meta": {}
  },
  "formation-1-musulman/niveau-1/episode-08-pieges-blocages-et-comment-les-depasser.md": {
    "title": "08. Pieges blocages et comment les depasser",
    "meta": {}
  },
  "formation-1-musulman/niveau-2/episode-01-al-fatiha-versets-1-3.md": {
    "title": "01. Al fatiha versets 1 3",
    "meta": {}
  },
  "formation-1-musulman/niveau-2/episode-02-al-fatiha-versets-4-5.md": {
    "title": "02. Al fatiha versets 4 5",
    "meta": {}
  },
  "formation-1-musulman/niveau-2/episode-03-al-fatiha-versets-6-7.md": {
    "title": "03. Al fatiha versets 6 7",
    "meta": {}
  },
  "formation-1-musulman/niveau-2/episode-04-tresors-versets-peur-et-anxiete.md": {
    "title": "04. Tresors versets peur et anxiete",
    "meta": {}
  },
  "formation-1-musulman/niveau-2/episode-05-tresors-versets-tristesse-et-deuil.md": {
    "title": "05. Tresors versets tristesse et deuil",
    "meta": {}
  },
  "formation-1-musulman/niveau-2/episode-06-tresors-versets-colere-et-culpabilite.md": {
    "title": "06. Tresors versets colere et culpabilite",
    "meta": {}
  },
  "formation-1-musulman/niveau-2/episode-07-noms-divins-outils-de-transformation.md": {
    "title": "07. Noms divins outils de transformation",
    "meta": {}
  },
  "formation-1-musulman/niveau-2/episode-08-pratique-quotidienne-avancee.md": {
    "title": "08. Pratique quotidienne avancee",
    "meta": {}
  },
  "formation-1-musulman/niveau-3/episode-01-le-point-noir-fana-intensif.md": {
    "title": "01. Le point noir fana intensif",
    "meta": {}
  },
  "formation-1-musulman/niveau-3/episode-02-le-dhikr-du-coeur.md": {
    "title": "02. Le dhikr du coeur",
    "meta": {}
  },
  "formation-1-musulman/niveau-3/episode-03-noms-divins-inversion-avancee.md": {
    "title": "03. Noms divins inversion avancee",
    "meta": {}
  },
  "formation-1-musulman/niveau-3/episode-04-les-etats-spirituels.md": {
    "title": "04. Les etats spirituels",
    "meta": {}
  },
  "formation-1-musulman/niveau-3/episode-05-qiyam-al-layl.md": {
    "title": "05. Qiyam al layl",
    "meta": {}
  },
  "formation-1-musulman/niveau-3/episode-06-muraqaba-la-veille-du-coeur.md": {
    "title": "06. Muraqaba la veille du coeur",
    "meta": {}
  },
  "formation-1-musulman/niveau-3/episode-07-les-4-phases-integrees.md": {
    "title": "07. Les 4 phases integrees",
    "meta": {}
  },
  "formation-1-musulman/niveau-3/episode-08-programme-40-jours.md": {
    "title": "08. Programme 40 jours",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-1/episode-01-pourquoi-votre-spiritualite-ne-survit-pas-au-travail.md": {
    "title": "01. Pourquoi votre spiritualite ne survit pas au travail",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-1/episode-02-les-fondations-5-regles-pour-le-pro.md": {
    "title": "02. Les fondations 5 regles pour le pro",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-1/episode-03-fana-leffacement-entre-deux-reunions.md": {
    "title": "03. Fana leffacement entre deux reunions",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-1/episode-04-tajalli-le-coran-au-bureau.md": {
    "title": "04. Tajalli le coran au bureau",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-1/episode-05-munajat-decisions-difficiles.md": {
    "title": "05. Munajat decisions difficiles",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-1/episode-06-la-beance-le-silence-au-travail.md": {
    "title": "06. La beance le silence au travail",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-1/episode-07-programme-14-jours-integration-pro.md": {
    "title": "07. Programme 14 jours integration pro",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-1/episode-08-pieges-du-professionnel.md": {
    "title": "08. Pieges du professionnel",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-2/episode-01-al-fatiha-versets-1-3-sens-au-travail.md": {
    "title": "01. Al fatiha versets 1 3 sens au travail",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-2/episode-02-al-fatiha-versets-4-5-servitude-et-guidance.md": {
    "title": "02. Al fatiha versets 4 5 servitude et guidance",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-2/episode-03-al-fatiha-versets-6-7-deux-extremes.md": {
    "title": "03. Al fatiha versets 6 7 deux extremes",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-2/episode-04-tresors-burnout-et-epuisement.md": {
    "title": "04. Tresors burnout et epuisement",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-2/episode-05-tresors-syndrome-imposteur.md": {
    "title": "05. Tresors syndrome imposteur",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-2/episode-06-tresors-conflits-et-autorite.md": {
    "title": "06. Tresors conflits et autorite",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-2/episode-07-noms-divins-outils-de-leadership.md": {
    "title": "07. Noms divins outils de leadership",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-2/episode-08-pratique-integree-avancee.md": {
    "title": "08. Pratique integree avancee",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-3/episode-01-point-noir-pro.md": {
    "title": "01. Point noir pro",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-3/episode-02-dhikr-du-coeur-au-bureau.md": {
    "title": "02. Dhikr du coeur au bureau",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-3/episode-02-dhikrru-coeur-au-bureau.md": {
    "title": "02. Dhikrru coeur au bureau",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-3/episode-03-inversion-avancee.md": {
    "title": "03. Inversion avancee",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-3/episode-04-etats-spirituels-au-travail.md": {
    "title": "04. Etats spirituels au travail",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-3/episode-05-qiyam-adapte-pour-les-pros.md": {
    "title": "05. Qiyam adapte pour les pros",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-3/episode-06-muraqaba-pro.md": {
    "title": "06. Muraqaba pro",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-3/episode-07-seance-integree.md": {
    "title": "07. Seance integree",
    "meta": {}
  },
  "formation-2-musulman-professionnel/niveau-3/episode-08-programme-40-jours-pro.md": {
    "title": "08. Programme 40 jours pro",
    "meta": {}
  },
  "formation-3-tout-public/nuveau-3/episode-05-meditation-avancee.md": {
    "title": "05. Meditation avancee",
    "meta": {}
  },
  "formation-3-tout-public/niveau-1/episode-01-pourquoi-la-spiritualite-est-elle-importante.md": {
    "title": "01. Pourquoi la spiritualite est elle importante",
    "meta": {}
  },
  "formation-3-tout-public/niveau-1/episode-02-les-fondations-cinq-pratiques.md": {
    "title": "02. Les fondations cinq pratiques",
    "meta": {}
  },
  "formation-3-tout-public/niveau-1/episode-03-le-silence-interieur.md": {
    "title": "03. Le silence interieur",
    "meta": {}
  },
  "formation-3-tout-public/niveau-1/episode-04-tajalli-les-moments-de-clarte.md": {
    "title": "04. Tajalli les moments de clarte",
    "meta": {}
  },
  "formation-3-tout-public/niveau-1/episode-05-munajat-le-dialogue-avec-votre-sagesse.md": {
    "title": "05. Munajat le dialogue avec votre sagesse",
    "meta": {}
  },
  "formation-3-tout-public/niveau-1/episode-06-la-beance-lespace-de-transformation.md": {
    "title": "06. La beance lespace de transformation",
    "meta": {}
  },
  "formation-3-tout-public/niveau-1/episode-07-programme-14-jours.md": {
    "title": "07. Programme 14 jours",
    "meta": {}
  },
  "formation-3-tout-public/niveau-1/episode-08-pieges-et-blocages.md": {
    "title": "08. Pieges et blocages",
    "meta": {}
  },
  "formation-3-tout-public/niveau-2/episode-01-accueillir-les-emotions-sans-se-laisser-submerger.md": {
    "title": "01. Accueillir les emotions sans se laisser submerger",
    "meta": {}
  },
  "formation-3-tout-public/niveau-2/episode-01-accueillir-les-emotions.md": {
    "title": "01. Accueillir les emotions",
    "meta": {}
  },
  "formation-3-tout-public/niveau-2/episode-02-transformer-la-peur-en-force-science-du-courage.md": {
    "title": "02. Transformer la peur en force science du courage",
    "meta": {}
  },
  "formation-3-tout-public/niveau-2/episode-02-transformer-la-peur.md": {
    "title": "02. Transformer la peur",
    "meta": {}
  },
  "formation-3-tout-public/niveau-2/episode-03-les-relations-difficiles-communication-et-compassion.md": {
    "title": "03. Les relations difficiles communication et compassion",
    "meta": {}
  },
  "formation-3-tout-public/niveau-2/episode-03-relations-difficiles.md": {
    "title": "03. Relations difficiles",
    "meta": {}
  },
  "formation-3-tout-public/niveau-2/episode-04-le-sens-de-la-vie-construire-un-pourquoi.md": {
    "title": "04. Le sens de la vie construire un pourquoi",
    "meta": {}
  },
  "formation-3-tout-public/niveau-2/episode-04-le-sens-de-la-vie.md": {
    "title": "04. Le sens de la vie",
    "meta": {}
  },
  "formation-3-tout-public/niveau-2/episode-05-la-resilience-rebondir-apres-epreuve.md": {
    "title": "05. La resilience rebondir apres epreuve",
    "meta": {}
  },
  "formation-3-tout-public/niveau-2/episode-05-la-resilience.md": {
    "title": "05. La resilience",
    "meta": {}
  },
  "formation-3-tout-public/niveau-2/episode-06-le-lacher-prise-detachement-et-confiance.md": {
    "title": "06. Le lacher prise detachement et confiance",
    "meta": {}
  },
  "formation-3-tout-public/niveau-2/episode-06-le-lacher-prise.md": {
    "title": "06. Le lacher prise",
    "meta": {}
  },
  "formation-3-tout-public/niveau-2/episode-07-pratiques-avancees-micro-retraite-et-techniques.md": {
    "title": "07. Pratiques avancees micro retraite et techniques",
    "meta": {}
  },
  "formation-3-tout-public/niveau-2/episode-07-pratiques-avancees.md": {
    "title": "07. Pratiques avancees",
    "meta": {}
  },
  "formation-3-tout-public/niveau-2/episode-08-seance-integree-n2.md": {
    "title": "08. Seance integree n2",
    "meta": {}
  },
  "formation-3-tout-public/niveau-2/episode-08-seance-integree-routine-complete-de-la-journee.md": {
    "title": "08. Seance integree routine complete de la journee",
    "meta": {}
  },
  "formation-3-tout-public/niveau-3/episode-01-votre-point-faible.md": {
    "title": "01. Votre point faible",
    "meta": {}
  },
  "formation-3-tout-public/niveau-3/episode-02-presence-au-quotidien.md": {
    "title": "02. Presence au quotidien",
    "meta": {}
  },
  "formation-3-tout-public/niveau-3/episode-03-pensees-negatives-inversion.md": {
    "title": "03. Pensees negatives inversion",
    "meta": {}
  },
  "formation-3-tout-public/niveau-3/episode-04-les-etats-de-conscience-flow.md": {
    "title": "04. Les etats de conscience flow",
    "meta": {}
  },
  "formation-3-tout-public/niveau-3/episode-05-meditation-avancee.md": {
    "title": "05. Meditation avancee",
    "meta": {}
  },
  "formation-3-tout-public/niveau-3/episode-06-la-pratique-du-matin-integrale-routine-complete.md": {
    "title": "06. La pratique du matin integrale routine complete",
    "meta": {}
  },
  "formation-3-tout-public/niveau-3/episode-07-seance-integree.md": {
    "title": "07. Seance integree",
    "meta": {}
  },
  "formation-3-tout-public/niveau-3/episode-08-programme-40-jours.md": {
    "title": "08. Programme 40 jours",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-1/episode-01-pourquoi-spiritualite-pro.md": {
    "title": "01. Pourquoi spiritualite pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-1/episode-02-fondations-pro.md": {
    "title": "02. Fondations pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-1/episode-03-le-silence-interieur-pro.md": {
    "title": "03. Le silence interieur pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-1/episode-04-tajalli-bureau.md": {
    "title": "04. Tajalli bureau",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-1/episode-05-munajat-decisions.md": {
    "title": "05. Munajat decisions",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-1/episode-06-lespace-de-transformation-pro.md": {
    "title": "06. Lespace de transformation pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-1/episode-07-programme-14-jours-pro.md": {
    "title": "07. Programme 14 jours pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-1/episode-08-seance-integree-initiation-pro.md": {
    "title": "08. Seance integree initiation pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-1/episode-08-seance-n2-pro.md": {
    "title": "08. Seance n2 pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-2/episode-01-burnout-pro.md": {
    "title": "01. Burnout pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-2/episode-02-imposteur-pro.md": {
    "title": "02. Imposteur pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-2/episode-03-leadership-empathie.md": {
    "title": "03. Leadership empathie",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-2/episode-04-conflits-pro.md": {
    "title": "04. Conflits pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-2/episode-05-sens-travail.md": {
    "title": "05. Sens travail",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-2/episode-06-resilience-pro.md": {
    "title": "06. Resilience pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-2/episode-07-pratiques-avancees-pro.md": {
    "title": "07. Pratiques avancees pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-2/episode-08-seance-n2-pro.md": {
    "title": "08. Seance n2 pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-3/episode-01-point-faible-pro.md": {
    "title": "01. Point faible pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-3/episode-02-presence-pro.md": {
    "title": "02. Presence pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-3/episode-03-pensees-negatives-pro.md": {
    "title": "03. Pensees negatives pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-3/episode-04-etats-flow-pro.md": {
    "title": "04. Etats flow pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-3/episode-05-meditation-avancee-pro.md": {
    "title": "05. Meditation avancee pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-3/episode-06-routine-matinale-pro.md": {
    "title": "06. Routine matinale pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-3/episode-07-seance-integree-pro.md": {
    "title": "07. Seance integree pro",
    "meta": {}
  },
  "formation-4-pro-tout-public/niveau-3/episode-08-programme-40-jours-pro.md": {
    "title": "08. Programme 40 jours pro",
    "meta": {}
  },
  "formation-5-parents-musulmans/niveau-1-compagnonnage-spirituel/episode-01-ce-que-votre-ado-musulman-vit.md": {
    "title": "01. Ce que votre ado musulman vit",
    "meta": {}
  },
  "formation-5-parents-musulmans/niveau-1-compagnonnage-spirituel/episode-02-votre-ado-vous-lit-avant-de-lire-le-coran.md": {
    "title": "02. Votre ado vous lit avant de lire le coran",
    "meta": {}
  },
  "formation-5-parents-musulmans/niveau-1-compagnonnage-spirituel/episode-03-votre-ado-est-en-guerre-avec-deux-mondes.md": {
    "title": "03. Votre ado est en guerre avec deux mondes",
    "meta": {}
  },
  "formation-5-parents-musulmans/niveau-1-compagnonnage-spirituel/episode-04-quil-prie-5-fois-ou-0-fois.md": {
    "title": "04. Quil prie 5 fois ou 0 fois",
    "meta": {}
  },
  "formation-5-parents-musulmans/niveau-1-compagnonnage-spirituel/episode-05-quand-la-porte-claque.md": {
    "title": "05. Quand la porte claque",
    "meta": {}
  },
  "formation-5-parents-musulmans/niveau-1-compagnonnage-spirituel/episode-06-langoisse-nest-pas-un-manque-de-foi.md": {
    "title": "06. Langoisse nest pas un manque de foi",
    "meta": {}
  },
  "formation-5-parents-musulmans/niveau-1-compagnonnage-spirituel/episode-07-ce-que-votre-ado-cherche-sur-son-telephone.md": {
    "title": "07. Ce que votre ado cherche sur son telephone",
    "meta": {}
  },
  "formation-5-parents-musulmans/niveau-1-compagnonnage-spirituel/episode-08-devenir-le-parent-qui-accompagne.md": {
    "title": "08. Devenir le parent qui accompagne",
    "meta": {}
  },
  "formation-6-parents-tout-public/niveau-1-presence-parentale/episode-01-derriere-le-masque-de-votre-ado.md": {
    "title": "01. Derriere le masque de votre ado",
    "meta": {}
  },
  "formation-6-parents-tout-public/niveau-1-presence-parentale/episode-02-votre-ado-repete-ce-que-vous-navez-pas-regle.md": {
    "title": "02. Votre ado repete ce que vous navez pas regle",
    "meta": {}
  },
  "formation-6-parents-tout-public/niveau-1-presence-parentale/episode-03-limposteur-commence-a-14-ans.md": {
    "title": "03. Limposteur commence a 14 ans",
    "meta": {}
  },
  "formation-6-parents-tout-public/niveau-1-presence-parentale/episode-04-le-corps-de-votre-ado-parle.md": {
    "title": "04. Le corps de votre ado parle",
    "meta": {}
  },
  "formation-6-parents-tout-public/niveau-1-presence-parentale/episode-05-quand-votre-ado-vous-rejette.md": {
    "title": "05. Quand votre ado vous rejette",
    "meta": {}
  },
  "formation-6-parents-tout-public/niveau-1-presence-parentale/episode-06-lanxiete-a-quelque-chose-a-vous-dire.md": {
    "title": "06. Lanxiete a quelque chose a vous dire",
    "meta": {}
  },
  "formation-6-parents-tout-public/niveau-1-presence-parentale/episode-07-lennui-est-mort.md": {
    "title": "07. Lennui est mort",
    "meta": {}
  },
  "formation-6-parents-tout-public/niveau-1-presence-parentale/episode-08-vous-ne-pouvez-offrir-que-ce-que-vous-avez-cultive.md": {
    "title": "08. Vous ne pouvez offrir que ce que vous avez cultive",
    "meta": {}
  },
  "formation-7-parents-musulmans-7-11/niveau-1-la-preservation/episode-01-le-miroir-liquide-pourquoi-7-11-ans-est-la-periode-la-plus-dangereuse.md": {
    "title": "01. Le miroir liquide pourquoi 7 11 ans est la periode la plus dangereuse",
    "meta": {}
  },
  "formation-7-parents-musulmans-7-11/niveau-1-la-preservation/episode-02-la-premiere-chose-que-votre-enfant-perd.md": {
    "title": "02. La premiere chose que votre enfant perd",
    "meta": {}
  },
  "formation-7-parents-musulmans-7-11/niveau-1-la-preservation/episode-03-quand-vous-criez-le-cerveau-de-votre-enfant-se-recable.md": {
    "title": "03. Quand vous criez le cerveau de votre enfant se recable",
    "meta": {}
  },
  "formation-7-parents-musulmans-7-11/niveau-1-la-preservation/episode-04-lecran-ne-vole-pas-le-temps-mais-la-capacite-a-ressentir.md": {
    "title": "04. Lecran ne vole pas le temps mais la capacite a ressentir",
    "meta": {}
  },
  "formation-7-parents-musulmans-7-11/niveau-1-la-preservation/episode-05-le-dua-de-votre-enfant-ne-devrait-jamais-etre-une-performance.md": {
    "title": "05. Le dua de votre enfant ne devrait jamais etre une performance",
    "meta": {}
  },
  "formation-7-parents-musulmans-7-11/niveau-1-la-preservation/episode-06-la-fratrie-nest-pas-un-probleme-cest-le-laboratoire-ou-la-fitra-se-teste.md": {
    "title": "06. La fratrie nest pas un probleme cest le laboratoire ou la fitra se teste",
    "meta": {}
  },
  "formation-7-parents-musulmans-7-11/niveau-1-la-preservation/episode-07-votre-enfant-vit-dans-deux-mondes-et-la-porte-entre-les-deux-est-en-train-de-se-fermer.md": {
    "title": "07. Votre enfant vit dans deux mondes et la porte entre les deux est en train de se fermer",
    "meta": {}
  },
  "formation-7-parents-musulmans-7-11/niveau-1-la-preservation/episode-08-les-5-piliers-de-la-preservation-votre-checklist-avant-12-ans.md": {
    "title": "08. Les 5 piliers de la preservation votre checklist avant 12 ans",
    "meta": {}
  },
  "formation-8-parents-tout-public-7-11/niveau-1-la-preservation/episode-01-la-fenetre-qui-ne-souvrira-quune-fois.md": {
    "title": "01. La fenetre qui ne souvrira quune fois",
    "meta": {}
  },
  "formation-8-parents-tout-public-7-11/niveau-1-la-preservation/episode-02-ca-va-les-12-emotions-desapprises.md": {
    "title": "02. Ca va les 12 emotions desapprises",
    "meta": {}
  },
  "formation-8-parents-tout-public-7-11/niveau-1-la-preservation/episode-03-votre-cerveau-sous-stress.md": {
    "title": "03. Votre cerveau sous stress",
    "meta": {}
  },
  "formation-8-parents-tout-public-7-11/niveau-1-la-preservation/episode-04-le-cerveau-face-aux-ecrans.md": {
    "title": "04. Le cerveau face aux ecrans",
    "meta": {}
  },
  "formation-8-parents-tout-public-7-11/niveau-1-la-preservation/episode-05-le-jeu-libre-est-un-acte-neurologique.md": {
    "title": "05. Le jeu libre est un acte neurologique",
    "meta": {}
  },
  "formation-8-parents-tout-public-7-11/niveau-1-la-preservation/episode-06-le-conflit-est-la-meilleure-ecole.md": {
    "title": "06. Le conflit est la meilleure ecole",
    "meta": {}
  },
  "formation-8-parents-tout-public-7-11/niveau-1-la-preservation/episode-07-lanxiete-de-performance-commence-a-8-ans.md": {
    "title": "07. Lanxiete de performance commence a 8 ans",
    "meta": {}
  },
  "formation-8-parents-tout-public-7-11/niveau-1-la-preservation/episode-08-les-5-competences-avant-12-ans.md": {
    "title": "08. Les 5 competences avant 12 ans",
    "meta": {}
  },
  "formation-9-enfants-musulmans-9-12/niveau-1-le-voyage-du-miroir/episode-01-ton-jardin-secret-territoire-1-l-appel.md": {
    "title": "01. Ton jardin secret territoire 1 l appel",
    "meta": {}
  },
  "formation-9-enfants-musulmans-9-12/niveau-1-le-voyage-du-miroir/episode-02-les-visiteurs-de-ton-jardin-territoire-2-la-carte.md": {
    "title": "02. Les visiteurs de ton jardin territoire 2 la carte",
    "meta": {}
  },
  "formation-9-enfants-musulmans-9-12/niveau-1-le-voyage-du-miroir/episode-03-quand-le-feu-monte-territoire-3-le-dragon.md": {
    "title": "03. Quand le feu monte territoire 3 le dragon",
    "meta": {}
  },
  "formation-9-enfants-musulmans-9-12/niveau-1-le-voyage-du-miroir/episode-04-la-salle-des-miroirs-territoire-4-les-amis.md": {
    "title": "04. La salle des miroirs territoire 4 les amis",
    "meta": {}
  },
  "formation-9-enfants-musulmans-9-12/niveau-1-le-voyage-du-miroir/episode-05-le-tresor-cache-territoire-5-la-gratitude.md": {
    "title": "05. Le tresor cache territoire 5 la gratitude",
    "meta": {}
  },
  "formation-9-enfants-musulmans-9-12/niveau-1-le-voyage-du-miroir/episode-06-la-nuit-etoilee-territoire-6-la-solitude.md": {
    "title": "06. La nuit etoilee territoire 6 la solitude",
    "meta": {}
  },
  "formation-9-enfants-musulmans-9-12/niveau-1-le-voyage-du-miroir/episode-07-le-labyrinthe-territoire-7-les-ecrans.md": {
    "title": "07. Le labyrinthe territoire 7 les ecrans",
    "meta": {}
  },
  "formation-9-enfants-musulmans-9-12/niveau-1-le-voyage-du-miroir/episode-08-la-cle-territoire-8-la-cloture.md": {
    "title": "08. La cle territoire 8 la cloture",
    "meta": {}
  },
  "formation-10-enfants-tout-public-9-12/niveau-1-le-voyage-du-miroir/episode-01-ton-chateau-interieur.md": {
    "title": "01. Ton chateau interieur",
    "meta": {}
  },
  "formation-10-enfants-tout-public-9-12/niveau-1-le-voyage-du-miroir/episode-02-les-messagers-de-ton-corps.md": {
    "title": "02. Les messagers de ton corps",
    "meta": {}
  },
  "formation-10-enfants-tout-public-9-12/niveau-1-le-voyage-du-miroir/episode-03-quand-le-volcan-éclate.md": {
    "title": "03. Quand le volcan éclate",
    "meta": {}
  },
  "formation-10-enfants-tout-public-9-12/niveau-1-le-voyage-du-miroir/episode-04-les-amis-miroirs.md": {
    "title": "04. Les amis miroirs",
    "meta": {}
  },
  "formation-10-enfants-tout-public-9-12/niveau-1-le-voyage-du-miroir/episode-05-le-muscle-de-la-gratitude.md": {
    "title": "05. Le muscle de la gratitude",
    "meta": {}
  },
  "formation-10-enfants-tout-public-9-12/niveau-1-le-voyage-du-miroir/episode-06-quand-tu-te-sens-seul-e.md": {
    "title": "06. Quand tu te sens seul e",
    "meta": {}
  },
  "formation-10-enfants-tout-public-9-12/niveau-1-le-voyage-du-miroir/episode-07-le-labyrinthe-decran.md": {
    "title": "07. Le labyrinthe decran",
    "meta": {}
  },
  "formation-10-enfants-tout-public-9-12/niveau-1-le-voyage-du-miroir/episode-08-la-cle.md": {
    "title": "08. La cle",
    "meta": {}
  }
} as Record<string, { title: string; meta: Record<string, string> }>
